FinalProject/Controllers/DocumentStreamController.cs
using FinalProject.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.IO;
using System.Text;
using System.Security.Cryptography;
using Mammoth;
using System.Text.RegularExpressions;

namespace FinalProject.Controllers
{
    public class DocumentStreamController : Controller
    {
        // GET: DocumentStream
        public ActionResult Index()
        {
            if (Session["set"] != null)
            {
                if ((bool)Session["set"] == true)
                {
                    return Redirect("/Dashboard");
                }
                else
                {
                    return Redirect("/Login?login=failed");
                }
            }
            else
            {
                return Redirect("/Login?login=loggedout");
            }
        }

        //Index is via post only since doc_id is required and if other doc_id which is not assigned to an user 
        //is acquired by the user then the user can see the details of the doc not assigned to him
        [HttpPost]
        public ActionResult Index(FormCollection fc)
        {
            if (Session["set"] != null)
            {
                if ((bool)Session["set"] == true)
                {
                    int doc_id = Convert.ToInt32(fc["doc_id"]);
                    Debug.WriteLine(doc_id);
                    int branch_id = GetMasterBranchId(doc_id);
                    ViewBag.DocId = doc_id;
                    ViewBag.DocTitle = GetDocumentName(doc_id);
                    ViewBag.CommitCount = GetDocCommitCount(doc_id);
                    ViewBag.IsMergedRequest = IfMergeRequestCloseBranch(doc_id);
                    var tupleModel = new Tuple<Dictionary<int,string>, List<Commit>>(GetBranchesOwnerOfDoc(doc_id), GetVersionHistoryOfBranch(branch_id));
                    return View(tupleModel);
                }
                else
                {
                    return Redirect("/Login?login=failed");
                }
            }
            else
            {
                return Redirect("/Login?login=loggedout");
            }
        }

        [HttpPost]
        public ActionResult UpdateCommits(int doc_id, int branch_owner_user_id)
        {
            int branch_id = 0;
            Debug.WriteLine(doc_id + " " + branch_owner_user_id);
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT branch_id FROM `branch` WHERE doc_id = @doc_id AND branch_owner_user_id = @user_id";
            query.Parameters.AddWithValue("@doc_id", doc_id);
            query.Parameters.AddWithValue("@user_id", branch_owner_user_id);
            MySqlDataReader fetchQuery;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
                Debug.WriteLine("Fetched");
                while (fetchQuery.Read())
                {
                    branch_id = Convert.ToInt32(fetchQuery["branch_id"]);
                }
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            Debug.WriteLine(branch_id);
            conn.Close();
            List<Commit> commits = GetVersionHistoryOfBranch(branch_id);
            return Json(JsonConvert.SerializeObject(commits));
        }

        public int GetMasterBranchId(int doc_id)
        {
            int branch_id = 0;
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT branch_id FROM `branch` WHERE doc_id = @doc_id AND is_deleted = 0 AND is_master_branch = 1";
            query.Parameters.AddWithValue("@doc_id", doc_id);
            MySqlDataReader fetchQuery;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            while (fetchQuery.Read())
            {
                branch_id = Convert.ToInt32(fetchQuery["branch_id"]);
            }
            conn.Close();
            return branch_id;
        }

        public string GetDocumentName(int doc_id)
        {
            string name = "";
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT document.doc_title FROM document WHERE document.doc_id = @doc_id AND is_deleted = 0";
            query.Parameters.AddWithValue("@doc_id", doc_id);
            MySqlDataReader fetchQuery;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            while (fetchQuery.Read())
            {
                name = fetchQuery["doc_title"].ToString();
            }
            conn.Close();
            return name;
        }

        public int GetDocCommitCount(int doc_id)
        {
            int count = 0;
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT COUNT(*) AS commit_count FROM document_versions WHERE branch_id IN (SELECT branch_id FROM branch WHERE branch.doc_id = @doc_id AND is_deleted = 0)";
            query.Parameters.AddWithValue("@doc_id", doc_id);
            MySqlDataReader fetchQuery;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            while (fetchQuery.Read())
            {
                count = Convert.ToInt32(fetchQuery["commit_count"]);
            }
            conn.Close();
            return count;            
        }

        public List<Commit> GetVersionHistoryOfBranch(int branch_id)
        {
            List<Commit> commits = new List<Commit>();
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT * FROM `document_versions` WHERE branch_id = @branch_id AND is_deleted = 0";
            query.Parameters.AddWithValue("@branch_id", branch_id);
            MySqlDataReader fetchQuery;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            while (fetchQuery.Read())
            {
                commits.Add(new Commit(Convert.ToInt32(fetchQuery["doc_version_id"].ToString()), fetchQuery["doc_version"].ToString() + "."+ fetchQuery["doc_subversion"].ToString() + "."+ fetchQuery["doc_revision_number"].ToString(), fetchQuery["doc_comment"].ToString(), DateTime.Parse(fetchQuery["doc_revision_date"].ToString())));
            }
            conn.Close();
            return commits;
        }

        public Dictionary<int,String> GetBranchesOwnerOfDoc(int doc_id)
        {
            Dictionary<int, String> branchOwners = new Dictionary<int, String>();
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT branch_owner_user_id,branch_name FROM `branch` WHERE is_deleted = 0 AND doc_id = @doc_id";
            query.Parameters.AddWithValue("@doc_id", doc_id);
            MySqlDataReader fetchQuery;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            while (fetchQuery.Read())
            {
                branchOwners.Add(Convert.ToInt32(fetchQuery["branch_owner_user_id"].ToString()), fetchQuery["branch_name"].ToString());
            }
            conn.Close();
            return branchOwners;
        }

        [HttpPost]
        public ActionResult isBranchUser(int user_id)
        {
            if ((int)Session["user_id"] == user_id)
            {
                return Json(new { result = "true"});
            }
            return Json(new { result = "false" });
        }

        public ActionResult DownloadFile(int doc_ver_id)
        {
            if (Session["set"] != null)
            {
                if ((bool)Session["set"] == true)
                {
                    Debug.WriteLine("I am here");
                    MySqlConnection conn = HomeController.conn();
                    MySqlCommand query = conn.CreateCommand();
                    query.CommandText = "SELECT document_versions.doc,document.doc_title FROM ((document INNER JOIN branch ON document.doc_id = branch.doc_id) INNER JOIN document_versions ON document_versions.branch_id = branch.branch_id) WHERE document_versions.doc_version_id = @doc_ver_id";
                    query.Parameters.AddWithValue("@doc_ver_id", doc_ver_id);
                    MySqlDataReader fetchQuery;
                    try
                    {
                        conn.Open();
                        fetchQuery = query.ExecuteReader();
                        Debug.WriteLine("Done");
                    }
                    catch (Exception e)
                    {

FinalProject/Controllers/MergeController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalProject.Controllers
{
    public class MergeController : Controller
    {
        // GET: Merge
        public ActionResult Index(int doc_id)
        {
            if (Session["set"] != null)
            {
                if ((bool)Session["set"] == true)
                {
                    ViewBag.DocId = doc_id;
                    return View(GetBranchNamesOnDocId(doc_id));
                }
                else
                {
                    return Redirect("/Login?login=failed");
                }
            }
            else
            {
                return Redirect("/Login?login=loggedout");
            }
        }

        public Dictionary<int,string> GetBranchNamesOnDocId(int doc_id)
        {
            Dictionary<int,string> branchNames = new Dictionary<int, string>();
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT branch_owner_user_id,branch_name FROM `branch` WHERE doc_id = @doc_id AND branch_owner_user_id != @user_id";
            query.Parameters.AddWithValue("@doc_id", doc_id);
            query.Parameters.AddWithValue("@user_id", (int)Session["user_id"]);
            try
            {
                conn.Open();
                MySqlDataReader fetchQuery = query.ExecuteReader();
                while (fetchQuery.Read())
                {
                    branchNames.Add(Convert.ToInt32(fetchQuery["branch_owner_user_id"]), fetchQuery["branch_name"].ToString());
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Errorrrr " + ex);
            }
            conn.Close();
            return branchNames;
        }

        public int GetBranchId(int doc_id, int branch_owner_user_id)
        {
            int branch_id = 0;
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT * FROM `branch` WHERE doc_id=@doc_id AND branch_owner_user_id = @branch_owner_user_id";
            query.Parameters.AddWithValue("@doc_id", doc_id);
            query.Parameters.AddWithValue("@branch_owner_user_id", branch_owner_user_id);
            MySqlDataReader fetchQuery;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            while (fetchQuery.Read())
            {
                branch_id = Convert.ToInt32(fetchQuery["branch_id"]);
            }
            conn.Close();
            return branch_id;
        }

        [HttpPost]
        public ActionResult MergeRequest(FormCollection fc)
        {
            Debug.WriteLine(fc["doc_id"]);
            Debug.WriteLine(fc["merge_branch_id"]);
            int requested_from_branch_id = GetBranchId(Convert.ToInt32(fc["doc_id"]), (int)Session["user_id"]);
            Debug.WriteLine(requested_from_branch_id);
            int requested_to_branch_id = GetBranchId(Convert.ToInt32(fc["doc_id"]), Convert.ToInt32(fc["merge_branch_id"]));
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "INSERT INTO `merge_request`(`requested_from`, `requested_to`, `requested_from_branch_id`, `requested_to_branch_id`, `status`, `action_performed`, `created_at`, `updated_at`) VALUES (@requested_from, @requested_to, @requested_from_branch_id, @requested_to_branch_id, @status, @action_performed, @created_at, @updated_at)";
            query.Parameters.AddWithValue("@requested_from", Session["user_id"]);
            query.Parameters.AddWithValue("@requested_to", fc["merge_branch_id"]);
            query.Parameters.AddWithValue("@requested_from_branch_id", requested_from_branch_id);
            query.Parameters.AddWithValue("@requested_to_branch_id", requested_to_branch_id);
            query.Parameters.AddWithValue("@status", 0);
            query.Parameters.AddWithValue("@action_performed", 0);
            query.Parameters.AddWithValue("@created_at", DateTime.Now);
            query.Parameters.AddWithValue("@updated_at", DateTime.Now);
            int rowsAffected = 0;
            try
            {
                conn.Open();
                rowsAffected = query.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Debug.WriteLine("Exception branch fetch" + e);
            }
            conn.Close();
            return Redirect("/MergeRequest/SentMergeRequest");
        }

    }
}

FinalProject/Views/DocumentStream/Index.cshtml
@{
    ViewBag.Title = "Document Repository";
}
@model Tuple<Dictionary<int,string>, List<FinalProject.Models.Commit>>
<div id="app">
    <div class="main-wrapper">
        @Html.Partial("Navigation")

        <!-- Main Content -->
        <div class="main-content">
            <section class="section">

                <div class="section-header">
                    <h4>Version History - @ViewBag.DocTitle</h4>
                </div>
                <div class="card pt-4 card-primary">
                    <div class="row px-4">
                        <div class="form-group col-12 col-md-4 col-lg-4">
                            <select data-doc_id="@ViewBag.DocId" id="branch_select" class="form-control selectric" name="std_id" required>
                                @foreach (var item in Model.Item1)
                                {
                                    if (item.Value == "master")
                                    {
                                        <option value="@item.Key" selected>@item.Value</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Key">@item.Value</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="text-center">
                                <div class="badges ml-4 mt-1">
                                    <span class="badge badge-primary px-4_5 py-2 text-big">@ViewBag.CommitCount Commits</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="text-center">
                                <div class="badges ml-4 mt-1">
                                    <span class="badge badge-primary px-4_5 py-2 text-big">@Model.Item1.Count Branches</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body p-0 m-0 pt-3">
                        <div class="table-responsive table-invoice">
                            <table class="table table-striped" id="commit_table">
                                <thead>
                                    <tr>
                                        <th>Version</th>
                                        <th>Comment</th>
                                        <th>Last Commit On</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody id="commit_table_body">
                                    @foreach (var item in Model.Item2)
                                    {
                                        <tr class="commit_row">
                                            <td>@item.Version</td>
                                            <td>@item.Comment</td>
                                            <td>@item.RevDate</td>
                                            <td>
                                                <a href="@Url.Action("DownloadFile", "DocumentStream", new { doc_ver_id = item.Id })" class="btn btn-primary mr-2">
                                                    <i class="fa fa-download"></i>
                                                </a>
                                                <a href="#" class="btn btn-info mr-2" data-doc_ver_id="@item.Id">
                                                    <i class="fa fa-eye"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="float-right" id="actions" hidden>
                    <a href="@Url.Action("DownloadLatestFile","DocumentStream", new { doc_id = ViewBag.DocId })" class="btn btn-primary mr-2">Download Latest Version</a>
                    @if (!ViewBag.IsMergedRequest)
                    {
                        <a href="@Url.Action("UploadNewDocument","DocumentStream", new {route = "initial", doc_id = ViewBag.DocId})" class="btn btn-primary mr-2">Upload New Document</a>
                        <a href="@Url.Action("Index","Merge", new {doc_id = ViewBag.DocId})" class="btn btn-primary mr-2">Merge Branch</a>
                    }
                </div>
            </section>
        </div>
        @Html.Partial("Footer")
    </div>
</div>

FinalProject/Views/DocumentStream/UploadNewDocument.cshtml
@{
    ViewBag.Title = "Document Repository";
}
@model Tuple<Dictionary<int, string>, List<FinalProject.Models.Commit>>
<div id="app">
    <div class="main-wrapper">
        @Html.Partial("Navigation")

        <!-- Main Content -->
        <div class="main-content">
            <section class="section">

                <div class="section-header">
                    <h4>Upload New Version</h4>
                </div>
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm("DiffDocument", "DocumentStream", FormMethod.Post, new { enctype = "multipart/form-data", @class = "needs-validation", @novalidate = "" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="row">
                                <div class="form-group col-12 col-md-12 col-lg-9">
                                    <label>Upload New Document</label>
                                    <div class="form-control custom-file">
                                        <input type="file" name="book_doc" class="custom-file-input" id="customFile" required>
                                        <label class="custom-file-label" id="custom-file-name" for="customFile">Choose file</label>
                                    </div>
                                </div>
                                <input type="hidden" name="doc_id" value="@ViewBag.DocId">
                                <div class="col-lg-3 mt-4 text-right col-12 col-md-12">
                                    <button type="submit" class="btn btn-primary btn-lg btn-icon icon-right mt-1" tabindex="4">
                                        Upload Document
                                    </button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                @if (ViewBag.Route == "updoc")
                {
                    <div class="float-right">
                        <a href="@Url.Action("ViewDiff","DocumentStream")" class="btn btn-primary mr-2" target="_blank">View Difference</a>
                        <button class="btn btn-primary mr-2" id="commit_new_file" data-doc_id="@ViewBag.DocId">
                            Commit File
                        </button>
                    </div>
                }
            </section>
        </div>
        @Html.Partial("Footer")
    </div>
</div>
<form class="modal-part" id="modal-form-part">
    <div class="form-group col-12 col-md-12 col-lg-12">
        <label>Commit Comment</label>
        <input type="text" class="form-control" name="comment" required>
        <div class="invalid-feedback">
            Please fill in the comment
        </div>
    </div>
    <div class="form-group">
        <label class="form-label">Version Type</label>
        <div class="selectgroup w-100">
            <label class="selectgroup-item">
                <input type="radio" name="value" value="1" class="selectgroup-input">
                <span class="selectgroup-button">Major Version</span>
            </label>
            <label class="selectgroup-item">
                <input type="radio" name="value" value="2" class="selectgroup-input">
                <span class="selectgroup-button">Normal Commit</span>
            </label>
        </div>
    </div>
</form>
@using (Html.BeginForm("Index", "DocumentStream", FormMethod.Post, new { id = "route_final" }))
{
    <input type="hidden" value="@ViewBag.DocId" name="doc_id" />
}
@section scripts{
    <script>
        document.getElementById('customFile').onchange = function () {
            document.getElementById('custom-file-name').innerHTML = this.files[0].name;
        }
    </script>
    @if (ViewBag.Route == "error")
    {
        <script>
            iziToast.error({
                title: 'Error! File Uploaded Not Found',
                message: 'The file uploaded not found! Please upload a new version',
                position: 'topRight'
            });
        </script>
    }
}