FinalProject/Controllers/DashboardController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;
using MySql.Data.MySqlClient;
using Newtonsoft.Json;

namespace FinalProject.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            if (Session["set"] != null)
            {
                if ((bool)Session["set"] == true)
                {
                    return View(GetDocuments((int)Session["user_id"]));
                }
                else
                {
                    return Redirect("/Login?login=failed");
                }
            }
            else
            {
                return Redirect("/Login?login=loggedout");
            }
        }

        public List<CollaboratorDocument> GetDocuments(int user_id)
        {
            List<CollaboratorDocument> documents = new List<CollaboratorDocument>();
            ArrayList docIds = new ArrayList();
            MySqlConnection conn = HomeController.conn();
            MySqlConnection conn_inner = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            MySqlCommand inner_query_1 = conn.CreateCommand();
            MySqlCommand inner_query_2 = conn_inner.CreateCommand();
            query.CommandText = "SELECT branch_owner_user_id,doc_id FROM `branch` WHERE branch_owner_user_id = @user_id";
            query.Parameters.AddWithValue("@user_id", user_id);
            try
            {
                conn.Open();
                Debug.WriteLine("query");
                MySqlDataReader fetchQuery = query.ExecuteReader();
                while (fetchQuery.Read())
                {
                    int doc_id = Convert.ToInt32(fetchQuery["doc_id"].ToString());
                    docIds.Add(doc_id);
                }
                conn.Close();
                foreach (var doc_id in docIds)
                {
                    conn.Open();
                    inner_query_1.CommandText = "SELECT document.doc_id, board.board_name, standard.standard, subject.subject, level.level, language.language_name, document.doc_title FROM ((((((`document` INNER JOIN subj_lang_level ON subj_lang_level.subj_lang_level_id = document.subj_lang_level_id) INNER JOIN language On language.language_id = subj_lang_level.language_id) INNER JOIN level On subj_lang_level.level_id = level.level_id) INNER JOIN subject ON subj_lang_level.subject_id = subject.subject_id) INNER JOIN standard ON standard.standard_id = subject.standard_id) INNER JOIN board ON board.board_id = standard.board_id) WHERE doc_id = @doc_id";
                    inner_query_1.Parameters.Clear();
                    inner_query_1.Parameters.AddWithValue("@doc_id", doc_id);
                    Debug.WriteLine("inner query 1");
                    MySqlDataReader innerFQ_1 = inner_query_1.ExecuteReader();

                    conn_inner.Open();
                    inner_query_2.CommandText = "SELECT document_versions.updated_at, user.user_fullname, document_versions.doc_version, document_versions.doc_subversion, document_versions.doc_revision_number FROM ((`branch` INNER JOIN document_versions ON branch.branch_id = document_versions.branch_id) INNER JOIN user ON user.user_id = branch.branch_owner_user_id)  WHERE doc_id=@doc_id ORDER BY document_versions.updated_at DESC LIMIT 1";
                    inner_query_2.Parameters.Clear();
                    inner_query_2.Parameters.AddWithValue("@doc_id", doc_id);
                    Debug.WriteLine("inner query 2");
                    MySqlDataReader innerFQ_2 = inner_query_2.ExecuteReader();

                    Debug.WriteLine("Finished all");
                    while (innerFQ_1.Read() && innerFQ_2.Read())
                    {
                        documents.Add(new CollaboratorDocument(
                            Convert.ToInt32(innerFQ_1["doc_id"].ToString()),
                            innerFQ_1["doc_title"].ToString(),
                            innerFQ_1["board_name"].ToString(),
                            innerFQ_1["standard"].ToString(),
                            innerFQ_1["subject"].ToString(),
                            innerFQ_1["level"].ToString(),
                            innerFQ_1["language_name"].ToString(),
                            innerFQ_2["doc_version"].ToString() + "." + innerFQ_2["doc_subversion"].ToString() + "." + innerFQ_2["doc_revision_number"].ToString(),
                            innerFQ_2["updated_at"].ToString(),
                            innerFQ_2["user_fullname"].ToString()
                            )
                        );
                    }
                    conn.Close();
                    conn_inner.Close();
                }
            }
            catch (MySql.Data.MySqlClient.MySqlException exception)
            {
                Debug.WriteLine(exception.ToString());
            }
            return documents;
        }

        public ActionResult Logout()
        {
            Session["set"] = false;
            Session["email"] = null;
            Session["level"] = -1;
            Session["user_name"] = null;
            Session["user_fullname"] = null;
            Session["user_role"] = 0;
            return Redirect("/Login?login=loggedout");
        }

    }
}

FinalProject/Controllers/MergeRequestController.cs
using FinalProject.Models;
using MySql.Data.MySqlClient;
using OpenXmlPowerTools;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalProject.Controllers
{
    public class MergeRequestController : Controller
    {
        // GET: MergeRequest
        public ActionResult Index()
        {
            if (Session["set"] != null)
            {
                if ((bool)Session["set"] == true)
                {
                    return Redirect("/Dashboard");
                }
                else
                {
                    return Redirect("/Login?login=failed");
                }
            }
            else
            {
                return Redirect("/Login?login=loggedout");
            }
        }

        public ActionResult RecievedMergeRequest()
        {
            if (Session["set"] != null)
            {
                if ((bool)Session["set"] == true)
                {
                    MySqlConnection conn = HomeController.conn();
                    MySqlCommand query = conn.CreateCommand();
                    query.CommandText = "SELECT merge_request_id, user.user_fullname as un,comment, status,action_performed FROM merge_request INNER JOIN user where requested_to = @user_id and user.user_id = requested_from";
                    query.Parameters.AddWithValue("@user_id", Session["user_id"]);
                    MySqlDataReader fetchQuery;
                    try
                    {
                        conn.Open();
                        fetchQuery = query.ExecuteReader();
                    }
                    catch (Exception e)
                    {
                        fetchQuery = null;
                        Debug.WriteLine("Exception branchowners" + e);
                    }
                    List<MergeRequest> res = new List<MergeRequest>();
                    while (fetchQuery.Read())
                    {
                        //ap - 0 : pending     ap=1,status=0 : n    ap1s1=yes
                        if (Convert.ToInt32(fetchQuery["status"]) == 0 && Convert.ToInt32(fetchQuery["action_performed"]) == 1)
                        {
                            res.Add(new MergeRequest(Convert.ToInt32(fetchQuery["merge_request_id"]), (string)fetchQuery["un"], "Rejected", (string)fetchQuery["comment"]));
                        }
                        else if (Convert.ToInt32(fetchQuery["action_performed"]) == 0)
                        {
                            res.Add(new MergeRequest(Convert.ToInt32(fetchQuery["merge_request_id"]), (string)fetchQuery["un"], "Pending", (string)fetchQuery["comment"]));
                            //pending
                        }                        
                        else if (Convert.ToInt32(fetchQuery["status"]) == 1 && Convert.ToInt32(fetchQuery["action_performed"]) == 1)
                        {
                            res.Add(new MergeRequest(Convert.ToInt32(fetchQuery["merge_request_id"]), (string)fetchQuery["un"], "Accepted", (string)fetchQuery["comment"]));
                        }
                    }
                    conn.Close();
                    return View(res);
                }
                else
                {
                    return Redirect("/Login?login=failed");
                }
            }
            else
            {
                return Redirect("/Login?login=loggedout");
            }
        }

        public ActionResult SentMergeRequest()
        {
            if (Session["set"] != null)
            {
                if ((bool)Session["set"] == true)
                {
                    MySqlConnection conn = HomeController.conn();
                    MySqlCommand query = conn.CreateCommand();
                    query.CommandText = "SELECT merge_request_id, user.user_fullname as un,comment, status,action_performed FROM merge_request INNER JOIN user where requested_from = @user_id and user.user_id = requested_to";
                    query.Parameters.AddWithValue("@user_id", Session["user_id"]);
                    MySqlDataReader fetchQuery;
                    try
                    {
                        conn.Open();
                        fetchQuery = query.ExecuteReader();
                    }
                    catch (Exception e)
                    {
                        fetchQuery = null;
                        Debug.WriteLine("Exception branchowners" + e);
                    }
                    List<MergeRequest> res = new List<MergeRequest>();
                    while (fetchQuery.Read())
                    {
                        //ap - 0 : pending     ap=1,status=0 : n    ap1s1=yes
                        if (Convert.ToInt32(fetchQuery["status"]) == 0 && Convert.ToInt32(fetchQuery["action_performed"]) == 1)
                        {
                            res.Add(new MergeRequest(Convert.ToInt32(fetchQuery["merge_request_id"]), (string)fetchQuery["un"], "Rejected", (string)fetchQuery["comment"]));
                        }
                        else if (Convert.ToInt32(fetchQuery["action_performed"]) == 0)
                        {
                            res.Add(new MergeRequest(Convert.ToInt32(fetchQuery["merge_request_id"]), (string)fetchQuery["un"], "Pending", (string)fetchQuery["comment"]));
                            //pending
                        }
                        else if (Convert.ToInt32(fetchQuery["status"]) == 1 && Convert.ToInt32(fetchQuery["action_performed"]) == 1)
                        {
                            res.Add(new MergeRequest(Convert.ToInt32(fetchQuery["merge_request_id"]), (string)fetchQuery["un"], "Accepted", (string)fetchQuery["comment"]));
                        }
                    }
                    conn.Close();
                    return View(res);
                }
                else
                {
                    return Redirect("/Login?login=failed");
                }
            }
            else
            {
                return Redirect("/Login?login=loggedout");
            }
        }

        [HttpPost]
        public ActionResult RejectMergeRequest(int merge_Request_id, string comment)
        {
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "UPDATE `merge_request` SET `status`= 0,`action_performed`=1, comment=@comment WHERE merge_request_id = @merge_request_id";
            query.Parameters.AddWithValue("@comment", comment);
            query.Parameters.AddWithValue("@merge_request_id", merge_Request_id);
            int RowsAffected = -1;
            try
            {
                conn.Open();
                RowsAffected = query.ExecuteNonQuery();
                conn.Close();
                return Json(new { result = "success" });
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.ToString());
                return Json(new { result = "error" + e.ToString() });
            }
        }

        public void DownloadLatestFileOfBranchWithName(int branch_id, string title)
        {
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT * FROM `document_versions` WHERE branch_id = @branch_id ORDER BY doc_revision_date DESC LIMIT 1";
            query.Parameters.AddWithValue("@branch_id", branch_id);
            MySqlDataReader fetchQuery;
            byte[] doc_file = null;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            while (fetchQuery.Read())
            {
                doc_file = (byte[])fetchQuery["doc"];
            }
            conn.Close();
            System.IO.File.WriteAllBytes(Path.Combine(Server.MapPath("~/UploadedFiles/"), title + ".docx"), doc_file);
        }

        public void MergeFiles(string DirPath)
        {
            string path1 = DirPath + "requested_to.docx";
            string path2 = DirPath + "requested_from.docx";
            string op = DirPath + "merged.docx";

            byte[] arr1 = System.IO.File.ReadAllBytes(path1);
            byte[] arr2 = System.IO.File.ReadAllBytes(path2);

            var sources = new List<OpenXmlPowerTools.Source>();
            sources.Add(new OpenXmlPowerTools.Source(new WmlDocument("requested_to.docx", arr1)));
            sources.Add(new OpenXmlPowerTools.Source(new WmlDocument("requested_from.docx", arr2)));

            var mergedDoc = DocumentBuilder.BuildDocument(sources);
            mergedDoc.SaveAs(op);
        }

        public ActionResult AcceptMergeRequest(int merge_Request_id, string comment)
        {
            MySqlConnection conn = HomeController.conn();
            MySqlCommand query = conn.CreateCommand();
            query.CommandText = "SELECT requested_from_branch_id, requested_to_branch_id FROM `merge_request` WHERE merge_request_id = @merge_request_id";
            query.Parameters.AddWithValue("@merge_request_id", merge_Request_id);
            MySqlDataReader fetchQuery;
            int requested_from_bid = 0, requested_to_bid = 0;
            try
            {
                conn.Open();
                fetchQuery = query.ExecuteReader();
            }
            catch (Exception e)
            {
                fetchQuery = null;
                Debug.WriteLine("Exception branchowners" + e);
            }
            while (fetchQuery.Read())
            {
                requested_from_bid = Convert.ToInt32(fetchQuery["requested_from_branch_id"]);

FinalProject/Views/Shared/Footer.cshtml
<footer class="main-footer">
    <div class="simple-footer">
        Copyright &copy; 2019 <div class="bullet"></div> Design By <a href="#">Animesh Ghosh</a>
    </div>
</footer>

FinalProject/Views/Shared/Navigation.cshtml
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <a href="index.html" class="navbar-brand sidebar-gone-hide">
        <img src="~/Content/assets/img/logo.svg" alt="" width="125px">
    </a>
    <a href="#" class="nav-link sidebar-gone-show mt-4" data-toggle="sidebar"><i class="fas fa-bars fa-3x"></i></a>
    <div class="nav-collapse">
    </div>
    <form class="form-inline ml-auto"></form>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="~/Content/assets/img/avatar/avatar-1.png" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">Hi, @Session["user_fullname"]</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-title">Logged in 5 min ago</div>
                <a href="features-profile.html" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a>
                <a href="features-activities.html" class="dropdown-item has-icon">
                    <i class="fas fa-bolt"></i> Activities
                </a>
                <a href="features-settings.html" class="dropdown-item has-icon">
                    <i class="fas fa-cog"></i> Settings
                </a>
                <div class="dropdown-divider"></div>
                <a href="@Url.Action("Logout", "DashBoard")" class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
        </li>
    </ul>
</nav>
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand sidebar-gone-show">
            <a href="index.html">
                <img src="~/Content/assets/img/logo-dark.svg" alt="" width="80px">
            </a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li class="nav-item">
                <a href="@Url.Action("Index","Dashboard")" class="nav-link"><i class="fas fa-fire"></i><span>Dashboard</span></a>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Merge Requests</span></a>
                <ul class="dropdown-menu">
                    <li>
                        @Html.ActionLink("Recieved Merge Requests", "RecievedMergeRequest", "MergeRequest", null, new { @class = "nav-link" })
                    </li>
                    <li>
                        @Html.ActionLink("Sent Merge Requests", "SentMergeRequest", "MergeRequest", null, new { @class = "nav-link" })
                    </li>
                </ul>
            </li>
        </ul>
    </aside>
</div>

FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/icons")
    @Styles.Render("~/Content/dropdowns")
    @Styles.Render("~/Content/basecss")
    @Styles.Render("~/Content/toastrcss")
    @if (@ViewBag.Title == "Login")
    {
        @Styles.Render("~/Content/socialcss")
    }

</head>
<body class="layout-2">
    @RenderBody()

    @Scripts.Render("~/Content/basejs")
    @Scripts.Render("~/Content/vendorjs")
    @Scripts.Render("~/Content/toastr")

    @if (@ViewBag.Title == "Register")
    {
        @Scripts.Render("~/Content/register")
    }
    @if (ViewBag.Title == "Document Repository")
    {
        @Scripts.Render("~/Content/internal-pages")
    }
    @if (ViewBag.Title == "Received Merge Requests")
    {
        @Scripts.Render("~/Content/internal-pages")
    }

    @Scripts.Render("~/Content/templatejs")
    @RenderSection("scripts", required: false)
</body>
</html>